/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto_linguagem_leonardo;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author Aluno
 */
public class Projeto_Leonardo extends javax.swing.JFrame {

    /**
     * Creates new form Projeto_Leonardo
     */
    public Projeto_Leonardo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pgbDisco = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        pgbMemoria = new javax.swing.JProgressBar();
        pgbCPU = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMinCPU = new javax.swing.JLabel();
        lblMedCPU = new javax.swing.JLabel();
        lblMaxCPU = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        lblMaxDisco = new javax.swing.JLabel();
        lblMedDisco = new javax.swing.JLabel();
        lblMaxMemoria = new javax.swing.JLabel();
        lblMedMemoria = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblMinMemoria = new javax.swing.JLabel();
        btnMonitorar = new javax.swing.JButton();

        jLabel20.setText("0");

        jLabel21.setText("0");

        jLabel11.setText("MIN");

        jLabel12.setText("MED");

        jLabel13.setText("MAX");

        jLabel22.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Monitoramento da maquina");

        jLabel2.setText("CPU");

        jLabel3.setText("Disco");

        jLabel4.setText("Memoria");

        jLabel5.setText("MIN");

        jLabel6.setText("MED");

        jLabel7.setText("MAX");

        jLabel8.setText("MIN");

        jLabel9.setText("MED");

        jLabel10.setText("MAX");

        lblMinCPU.setText("0");

        lblMedCPU.setText("0");

        lblMaxCPU.setText("0");

        lblMinDisco.setText("0");

        lblMaxDisco.setText("0");

        lblMedDisco.setText("0");

        lblMaxMemoria.setText("0");

        lblMedMemoria.setText("0");

        jLabel25.setText("MIN");

        jLabel26.setText("MED");

        jLabel27.setText("MAX");

        lblMinMemoria.setText("0");

        btnMonitorar.setText("Monitorar");
        btnMonitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMinCPU))
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMedCPU)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMaxCPU))
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMedDisco)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMaxDisco))
                                    .addComponent(jLabel10))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblMinDisco))
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMinMemoria))
                                    .addComponent(jLabel25))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMedMemoria)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMaxMemoria))
                                    .addComponent(jLabel27))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnMonitorar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinCPU)
                            .addComponent(lblMedCPU)
                            .addComponent(lblMaxCPU))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinDisco)
                            .addComponent(lblMedDisco)
                            .addComponent(lblMaxDisco))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinMemoria)
                            .addComponent(lblMedMemoria)
                            .addComponent(lblMaxMemoria))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnMonitorar)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
// Variaveis de minimo e maximo das labels da CPU
    Integer numeromaxcpu = 0;
    Integer numeromincpu = 100;
    // Variaveis de minimo e maximo das labels da Memoria
    Integer numeromaxmemoria = 0;
    Integer numerominmemoria = 100;
    // Variaveis de minimo e maximo das labels do disco
    Integer numeromaxdisco = 0;
    Integer numeromindisco = 100;
    // comandos para definir a media ja dentro do botão e marcar o numero de "clicks"
    Integer cpumedia = 0;
    Integer medidorcpu = 0;
    Integer totalcpu = 0;
    Integer discomedia = 0;
    Integer medidordisco = 0;
    Integer totaldisco = 0;
    Integer memoriamedia = 0;
    Integer medidormemoria = 0;
    Integer totalmemoria = 0;
    
    //Professora, depois que eu executo o meu codigo e aperto o botão da ação, meu design da tela está sendo modificado...
    //nao consegui corrigir infelizmente :( 
    
    private void btnMonitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorarActionPerformed

        Random cpu = new Random();// criando variavel para numero randomico
        Integer cpunumero = cpu.nextInt(101);// usando a variavel de numeros inteiros para gerar um numero de 0 ate 100,99
        medidorcpu++ ; // comando para somar 1(um) sempre ao contador da CPU, para futuramente definir uma media
        totalcpu = totalcpu + cpunumero ;// o total da cpu seria o que ja está presente nela mais cada numero gerado a cada clique no "random"
        cpumedia = totalcpu / medidorcpu; // dividir sempre o total de vezes que o botão foi acionado pelos numeros gerados, para ter a média
        lblMedCPU.setText(String.format("%d",cpunumero));// exibir a media na label "lblMedCPU"
        lblMinCPU.setText((numeromincpu)+ "%");// exibir o minimo na label "lblMinCPU"
        lblMaxCPU.setText((numeromaxcpu)+ "%");// exibir o maximo na label "lblMaxCPU"
        lblMinCPU.setForeground(Color.red);// cor das labels
        lblMaxCPU.setForeground(Color.green);// cor das labels
        lblMedCPU.setForeground(Color.blue);// cor das labels
        pgbCPU.setValue(cpunumero);// definir ate onde vai a barra de progresso de acordo com o numero randomico gerado
        pgbCPU.setStringPainted(true);// permite eu inserir uma string dentro da barra de progresso "pgb"
        
        if(cpunumero > numeromaxcpu){ //se o numero gerado no aleatorio for maior que o numero maximo
            numeromaxcpu = cpunumero; // substituir o numero maximo pelo numero gerado na nova ação
        }
        if(cpunumero < numeromincpu){ // se o numero gerado for menor que o numero minimo
            numeromincpu = cpunumero; // substitur o numero minimo pelo numero gerado
        }
        
        lblMaxCPU.setText(String.format("%d%%",numeromaxcpu));
        lblMinCPU.setText(String.format("%d%%",numeromincpu));
        lblMedCPU.setText(String.format("%d%%",cpumedia));
        
        Random disco = new Random();
        Integer disconumero = disco.nextInt(101);
        medidordisco++ ; 
        totaldisco = totaldisco + disconumero ;
        discomedia = totaldisco / medidordisco;
        lblMedDisco.setText(String.format("%d",disconumero));
        lblMinDisco.setText((numeromindisco)+ "%");
        lblMaxDisco.setText((numeromaxdisco)+ "%");
        lblMinDisco.setForeground(Color.red);
        lblMaxDisco.setForeground(Color.green);
        lblMedDisco.setForeground(Color.blue);
        pgbDisco.setValue(disconumero);
        pgbDisco.setStringPainted(true);
        
        if(disconumero > numeromaxdisco){
            numeromaxdisco = disconumero;
        }
        if(disconumero < numeromindisco){
            numeromindisco = disconumero;
        }
        
        lblMaxDisco.setText(String.format("%d%%",numeromaxdisco));
        lblMinDisco.setText(String.format("%d%%",numeromindisco));
        lblMedDisco.setText(String.format("%d%%",discomedia));
        
        Random memoria = new Random();
        Integer memorianumero = memoria.nextInt(101);
        medidormemoria++ ; 
        totalmemoria = totalmemoria + memorianumero ;
        memoriamedia = totalmemoria / medidormemoria;
        lblMedMemoria.setText(String.format("%d",memorianumero));
        lblMinMemoria.setText((numerominmemoria)+ "%");
        lblMaxMemoria.setText((numeromaxmemoria)+ "%");
        lblMinMemoria.setForeground(Color.red);
        lblMaxMemoria.setForeground(Color.green);
        lblMedMemoria.setForeground(Color.blue);
        pgbMemoria.setValue(memorianumero);
        pgbMemoria.setStringPainted(true);
        
        if(memorianumero > numeromaxmemoria){
            numeromaxmemoria = memorianumero;
        }
        if(memorianumero < numerominmemoria){
            numerominmemoria = memorianumero;
        }
        
        lblMaxMemoria.setText(String.format("%d%%",numeromaxmemoria));
        lblMinMemoria.setText(String.format("%d%%",numerominmemoria));
        lblMedMemoria.setText(String.format("%d%%",memoriamedia));
    }//GEN-LAST:event_btnMonitorarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projeto_Leonardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projeto_Leonardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projeto_Leonardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projeto_Leonardo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto_Leonardo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMonitorar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMaxCPU;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxMemoria;
    private javax.swing.JLabel lblMedCPU;
    private javax.swing.JLabel lblMedDisco;
    private javax.swing.JLabel lblMedMemoria;
    private javax.swing.JLabel lblMinCPU;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinMemoria;
    private javax.swing.JProgressBar pgbCPU;
    private javax.swing.JProgressBar pgbDisco;
    private javax.swing.JProgressBar pgbMemoria;
    // End of variables declaration//GEN-END:variables
}
